from selenium.webdriver.common.by import By

# Locators
USER_AUTH_ICON = (By.XPATH, "//div[@class='flex h-8 items-center justify-center rounded-full bg-brand-solid px-4 text-[13px] font-semibold text-white transition hover:bg-brand-solid-hover active:scale-[0.97]']")
REGISTER_BTN = (By.XPATH, "//button[@type='button']")
FRST_NM_FLD = (By.XPATH, "//input[@id='firstName']")
LST_NM_FLD = (By.XPATH, "//input[@id='lastName']")
EML_FLD = (By.XPATH, "//input[@id='email']")
PSWRD_FLD = (By.XPATH, "//input[@id='password']")
REGISTER_USER_BTN = (By.XPATH, "//button[@type='submit']")
LGN_BTN = (By.XPATH, "//button[@type='submit']")
# REGISTERED_USR_LOGGED_LOGO = (By.XPATH, "//div[@class='text-primary font-medium text-[12px] md:text-[16px] overflow-hidden whitespace-nowrap sm:block hidden']")
REGISTERED_USR_LOGGED_LOGO = (By.XPATH, "//div[text() = 'Viachesla...']")
CLCK_ON_CART_ICN = (By.XPATH, "//a[@href='/cart']//div//*[name()='svg']")
SHPNG_CRT_TXT = (By.XPATH, "//h2[@class='mx-4 my-6 text-4xl']")
CNTNUE_SHPNG_BTN = (By.XPATH, "//a[normalize-space()='Continue Shopping']")
YR_CRT_IS_EMPTY = (By.XPATH, "//p[normalize-space()='Your cart is empty']")
ADD_TRKSH_CFFE = (By.XPATH, "/html[1]/body[1]/main[1]/section[2]/div[1]/ul[1]/li[2]/div[1]/div[2]/div[1]/button[1]/img[1]")
CRT_BTN_AFTR_ADDING = (By.XPATH, "//img[contains(@alt,'Cart')]")
CNTR_1_HERE = (By.XPATH, "//span[normalize-space()='1']")
TRKSH_CFF_IN_THE_CRT = (By.XPATH, "//p[normalize-space()='Turkish Coffee']")
FIVE_HNDRD_GRMS_TXT = (By.XPATH, "//p[contains(@class,'font-medium text-placeholder')]")
FOUR_HUNDRED_FORTY_NINE_DLRS = (By.XPATH, "//p[contains(@class,'right-0 top-0 text-lg font-semibold sm:absolute')]")
GO_TO_CHCK_OUT_BTN = (By.XPATH, "//a[text() = 'Go to checkout']")
FRGT_PSSWD = (By.XPATH, "//a[@class='text-sm text-brand hover:underline']")
ENTR_YR_EML_ADDRSS_FLD_RST_PSWD = (By.XPATH, "//input[@id='email']")
SND_RST_LNK = (By.XPATH, "//button[@type='submit']")
CNTNUE_TO_CNHG_YR_PSWRD = (By.XPATH, "//button[@type='button']")
CODE_FROM_EMAIL_FLD = (By.XPATH, "//input[@id='code']")
NEW_PASSWORD_FLD = (By.XPATH, "//input[@id='password']")
CNFRM_YR_PSWRD_FLD = (By.XPATH, "//input[@id='confirmPassword']")
RESET_PSWRD_BTN = (By.XPATH, "//button[@type='submit']")
INCORRECT_TOKEN_TEXT = (By.XPATH, "//div[@class='mt-4 text-negative']")
HEART_ICON_FAVORITIES = (By.XPATH, "///a[@aria-label='Open favourites']//div//*[name()='svg']")
HEART_VANILLA_LATTE = (By.XPATH, "//body/main/section/div/ul/li[1]/div[1]/div[1]/button[1]/img[1]")
HEART_TURKISH_COFFEE = (By.XPATH, "//body/main/section/div/ul/li[2]/div[1]/div[1]/button[1]/img[1]")
FOUR_POINT_FOURTY_NINE_DOLLARS = (By.XPATH, "//p[normalize-space()='$4.49']")
VANILLA_LATTE_TEXT = (By.XPATH, "//p[normalize-space()='Vanilla Latte']")
FOUR_POINT_EIGTHY_FIVE_DOLLARS = (By.XPATH, "//p[normalize-space()='$4.85']")




